@startuml
class LocalWasteStorage {
    + GetData(productId:string) : Task<WasteCollection>
    + <<async>> SaveData(productId:string, wasteCollection:WasteCollection) : Task
    RemoveWasteValue(wasteKey:string) : void
    SetWasteValue(wasteKey:string, value:int) : void
    GetWasteValue(wasteKey:string) : int?
    GetWasteValue(productId:string, wasteType:WasteType) : WasteAmount
}
IWasteStore <|-- LocalWasteStorage
@enduml
